### ISSUE TITLE
Footnote view example applies styles inconsistently

### ISSUE THREAD

**Issue by etherbob** [ProseMirror/website#105]
Selecting the heading options from the Type... menu applies to the outer paragraph and the inner footnote node even if just text in the inner node is selected. Not sure if this is an actual bug or just a misunderstanding of how the footnotes functionality is intended to behave.

**Comment by marijnh** [comment]
That demo only allows inline content in footnotes, so making the footnote a header wouldn't really mean anything. The menu is simply wired up to the outer editor, so it'll apply the block style you choose to that editor's selection (which is a node selection on the footnote node), even when you are in the inner editor. That's by design.

**Comment by etherbob** [comment]
Is it expected that the  text content of the footnote also gets styled as a header?

**Comment by marijnh** [comment]
That's embedded in the header in the DOM, so that's just the way CSS behaves by default. We could add a CSS rule to reset font size and weight, if you want you can create a PR.

**Comment by etherbob** [comment]
Ahh, I get it now. Thank you for clarifying. For our use case we started storing the footnote contents as a separate doc in a footnote attr. Easier to avoid unintended interactions between the two editor instances that way. We present the second editor via a modal overlay with a root element outside the existing PM instance which seems to do good job of keeping them separate.
