### ISSUE TITLE
Next Section link uses character that doesn't render in OS X Chrome

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/website#41]
The next section link uses the character ⮞ ("black rightwards equilateral arrowhead"). This character isn't available in Chrome on OS X and shows up as a Unicode square.

![screen shot 2016-10-25 at 12 45 22 pm](https://cloud.githubusercontent.com/assets/1087646/19695366/eaf1d68c-9ab0-11e6-927f-fdfe7de22af8.png)

**Comment by marijnh** [comment]
Ugh. Does it have ▶ ?

**Comment by ericandrewlewis** [comment]
Yep

![screen shot 2016-10-25 at 5 04 13 pm](https://cloud.githubusercontent.com/assets/1087646/19704274/15c5266a-9ad5-11e6-9678-d7c8076ee146.png)

**Comment by marijnh** [comment]
Hold on, does Safari render certain unicode characters are colorful emoji regardless of context, or is that github replacing it with an image? Probably not the latter, since it's a simple black triangle for me in the github comment. If so, that's also not really what I want.

Unicode is still hard, I guess. Is ➤ (a non-equilateral arrowhead) doing any better?

**Comment by ericandrewlewis** [comment]
> Hold on, does Safari render certain unicode characters are colorful emoji regardless of context, or is that github replacing it with an image?

All OS X browsers use the Apple Color Emoji font for all emoji. I guess ▶  (black right-pointing triangle) is [considered an emoji](http://unicode.org/emoji/charts/full-emoji-list.html#25b6).

➤ (Non-equilateral arrowhead) renders as you might expect it to:

![screen shot 2016-10-26 at 2 18 00 pm](https://cloud.githubusercontent.com/assets/1087646/19738895/0606dc7a-9b87-11e6-8cad-a7a788b85d64.png)

**Comment by marijnh** [comment]
Thanks!
