### ISSUE TITLE
Running locally, Demo's JavaScript returns 404

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/website#48]
If I run the website locally, opening any of the demo pages makes a 404 when the JS for the demo is requested.
![screen shot 2016-12-19 at 2 22 25 pm](https://cloud.githubusercontent.com/assets/1087646/21325954/a38ded8c-c5f6-11e6-8d27-c3dae0416cf1.png)

I notice although the given URL like `http://localhost:8888/moduleserve/mod/src/demo/basic` is a 404, I can access the JS at `http://localhost:8888/moduleserve/mod/__/src/demo/basic`.

**Comment by marijnh** [comment]
This doesn't happen for me. Could you give me a bit more info about how you run the server, which browser you use, etc?

**Comment by jldec** [comment]
I'm seeing the same issue running with devserver:

- serving with node v6.9.2, any browser
- cloned this repo, ran `npm install` and `make` 
  - for make to succeed i had to apply the [recent docs fix in prosemirror-state](https://github.com/ProseMirror/prosemirror-state/commit/64ab3b49acd7ecea60bcaaf0932b1bef17430f73) 
- then `npm run devserver -- --port 8888`

Debugging moduleserve/client.js (served as load.js) in the browser, it appears that the relative paths for the demo modules from [demoserver.js](https://github.com/ProseMirror/website/blob/master/src/demo/demoserver.js#L30-L36) are missing an extra `../` since the base for those demos is `public/demo/*`, not the website root in `public/`.
   
Changing those paths as follows, fixed this issue for me.

![screen shot 2016-12-30 at 9 37 44 am](https://cloud.githubusercontent.com/assets/849592/21566717/acf8490a-ce73-11e6-8229-4f89ac2e1cb1.png)

Happy to file a PR if that helps.

**Comment by jldec** [comment]
FYI - i just confirmed the same demo issue also occurs in the full dev setup (withthe same fix).

```
git clone git@github.com:ProseMirror/prosemirror.git
cd prosemirror
npm install (...wait for all the submodules etc.)
cd website
make
npm run devserver -- --port 8888
```

_In this case the website `make` succeeds without intervention because it pulls from the latest master branch version of prosemirror-state._

**Comment by marijnh** [comment]
Ah, oops, a bugfix in moduleserve had broken these. I've applied the proposed fix.
