### ISSUE TITLE
Footnote demo does not work in Safari (with solution)

### ISSUE THREAD

**Issue by frederik** [ProseMirror/website#86]
We noticed that the Footnote demo the tooltip does not work in Safari (Mac OS, Version 11.0.3 (13604.5.6)).

## Behavior
Tooltip opens but no cursor is visible. Text can not be changed.

## Expected
Text can be changed.

## Solution
Add
```
.footnote-tooltip {
    -webkit-user-select: text;
}
.ProseMirror {
    -webkit-user-select: text;
}
```
to the footnote-tooltip css class. It appears that Safari sets it to 'none' by default.

I would have submitted a pull request, but for some reasons make did not work to build the website. Here's the [glitch](https://glitch.com/edit/#!/enormous-output) where it is now working in Safari.

**Comment by frederik** [comment]
I solved the latter by also setting the property  on .ProseMirror (updated the original post). I am not suer why (and why now) this is coming up.

It only turned up with the new ProseMirror (on our .16 based implementation this is still working in Safari). So I am assuming some kind of css side-effect.

**Comment by marijnh** [comment]
The problem appears to be that the footnote's outer node is set to be draggable, which triggers a bunch of strange behavior for all its content in Safari, in a way that appears to be hard to disable. Attached patch turns off dragging for the footnote nodes, since that's not a terribly important feature here.
